name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    # FIXME: if the speed become problem, better to create original image.
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang llvm cmake ninja-build valgrind clang-format

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"


    - name: Check format for changed lines
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }} &&
        git diff -U0 ${{ github.event.pull_request.base.ref }} | clang-format-diff -p1 -style=LLVM | tee /dev/stderr | grep . && exit 1

    - name: Build
      run: |
        cmake -GNinja -Bbuild -DSANITIZE=ON -DCMAKE_BUILD_TYPE=Debug
        ninja -Cbuild

    - name: Run unit tests
      run: |
        ninja -Cbuild unittests

    - name: Assemble Test
      run: |
        ninja -Cbuild asmtest

    # FIXME: valgrind with clnag-14 seems like few problems exist.
    # https://github.com/google/sanitizers/issues/856
    # https://hg.mozilla.org/integration/autoland/rev/192810f500b5
    # - name: Run valgrind
    #   run: valgrind --leak-check=full --error-exitcode=1 build/asmkheiv tests/addi.s
